### ISSUE TITLE
When set frame: false, Minimize window is black

### ISSUE THREAD

**Issue by tonylu110** [GregVido/mica-electron#10]
I set `frame: false`, when I minimize window then open window, window will be black

**Comment by tonylu110** [comment]
[uyou-todo-electron](https://github.com/tonylu110/uyou-todo-electron)
This repo uses mica-electron, and like I say when I set `frame: false` background will be black

**Comment by GregVido** [comment]
Hello, I just made a commit which in theory fixes the problem 😁

**Comment by tonylu110** [comment]
> Hello, I just made a commit which in theory fixes the problem 😁

Oh, thanks. It can work for me. 
I have another question. How to set always use the light theme.

**Comment by GregVido** [comment]
Normally win.setLightTheme(); works for windows 11 effects.

**Comment by tonylu110** [comment]
> Normally win.setLightTheme(); works for windows 11 effects.

I know, but when I change the color theme. the window will change, and the background will be black.
I use `nativeTheme` to change light theme, but it won't work
```javascript
// it doesn't work
nativeTheme.on('updated', () => {
  mainWindow.setLightTheme()
})
```

**Comment by GregVido** [comment]
I just made an update, normally you don't need to use nativeTheme anymore, it's fixed 👍

**Comment by tonylu110** [comment]
> I just made an update, normally you don't need to use nativeTheme anymore, it's fixed 👍

Thanks, but it doesn't work. When I change color theme and background will be black.
Like this:
![](https://i.328888.xyz/2023/02/18/BSZud.png)

**Comment by GregVido** [comment]
Ok normally it's fixed (hopefully)

**Comment by tonylu110** [comment]
> Ok normally it's fixed (希望)

When I exit, it has a error
![](https://i.328888.xyz/2023/02/18/BTu2A.png)

**Comment by tonylu110** [comment]
> Ok normally it's fixed (hopefully)

When it exit, it has a error
![](https://i.328888.xyz/2023/02/18/BTu2A.png)

**Comment by GregVido** [comment]
Yes sorry it's fixed

**Comment by tonylu110** [comment]
> Yes sorry it's fixed

Oh yes, it's all work. Thanks
