### ISSUE TITLE
I think electron need in devDependencies，

### ISSUE THREAD

**Issue by tonylu110** [GregVido/mica-electron#11]
At hear
https://github.com/GregVido/mica-electron/blob/94ddedb94c87dae339b1ee0d383b3656016d4fe6/package.json#L30

When I packaged it also packaged electron in the result

**Comment by GregVido** [comment]
Yes sorry I will fix it

**Comment by GregVido** [comment]
Ok it's fixed

**Comment by tonylu110** [comment]
> Ok it's fixed

Thanks. It's all do
