### ISSUE TITLE
Use Windows 11 build, It can't run in Windows 10

### ISSUE THREAD

**Issue by tonylu110** [GregVido/mica-electron#12]
I set not windows 11 use `setCustomEffect`. It's only in Task Manager can see

**Comment by GregVido** [comment]
Sorry I don't understand, what you want say ?

**Comment by tonylu110** [comment]
> Sorry I don't understand, what you want say ?

The result I build on Windows 11 can't be used on Windows 10, it can only see the process in the task manager

**Comment by tonylu110** [comment]
It's my release https://github.com/tonylu110/uyou-todo-electron/releases/tag/1.1.7

**Comment by GregVido** [comment]
I watch this in the evening I can't currently

**Comment by GregVido** [comment]
Hello I don't have windows 10 so I can't try, next week I download windows 10 to emulate it

**Comment by tonylu110** [comment]
> Hello I don't have windows 10 so I can't try, next week I download windows 10 to emulate it

ok thanks

**Comment by tonylu110** [comment]
@GregVido Hello, Do you know how to solve this issue

**Comment by GregVido** [comment]
Hello, I found the problem

```js
  // mainWindow.setLightTheme()
  if (menuBlur || menuBlur === undefined) {
    if (IS_WINDOWS_11) {
      mainWindow.setMicaEffect()
    } else {
      // mainWindow.setRoundedCorner()
      mainWindow.setCustomEffect(4, '#fff6dc', 0.7);
    }
  } else {
    mainWindow.setCaptionColor('#fff6dc')
  }
```

mainWindow.setLightTheme() and mainWindow.setRoundedCorner() is for windows 11.

Sorry for the time, I'm a student and I don't have much time right now.

**Comment by tonylu110** [comment]
ok，thinks
