### ISSUE TITLE
titlebar background color is visible when frame: false

### ISSUE THREAD

**Issue by kamiya4047** [GregVido/mica-electron#13]
I have followed the [README.md](https://github.com/GregVido/mica-electron/blob/main/README.md) instructions and applied the Mica effect perfectly but the background color of the title bar destroyed the perfection.
Is there a way to disable the title bar background color?
I've tried `win.setCaptionColor()` but it doesn't take alpha values.
![image](https://user-images.githubusercontent.com/58339640/221403855-bc571c97-fd4e-4d57-b344-cdaaace881a2.png)

I'm on Windows 11 Home 22H2 with "Show accent color on title bars and windows borders" enabled in the Personalize Settings.

code https://github.com/ExpTechTW/TREM-RTS-Map/commit/3c42a02397122961fbed31abe599157a0ab13dd6

**Comment by GregVido** [comment]
Hello, I can't access your repo, but why you add a caption color if you dont want this ? If you remove all win.setCaptionColor you don't have color. You cannot remove a caption color because Windows 11 does not offer it.

**Comment by kamiya4047** [comment]
Repo is now public

I don't have `win.setCaptionColor()` in the code and the title bar background is there

https://github.com/ExpTechTW/TREM-RTS-Map/blob/3c42a02397122961fbed31abe599157a0ab13dd6/src/main.js#L8-L38

**Comment by GregVido** [comment]
When I try your repo it's work for me, what is your windows 11 version ?

![image](https://user-images.githubusercontent.com/52825262/221419441-3442256a-1a75-4d55-a52b-6356b19c1f59.png)

**Comment by kamiya4047** [comment]
Edition	Windows 11 Home
Version	22H2
Installed on	‎2023/‎01/‎21
OS build	22621.1194
Experience	Windows Feature Experience Pack 1000.22638.1000.0

![image](https://user-images.githubusercontent.com/58339640/221426335-b1e41a3a-c7cc-4b23-b48c-91889ce36b3a.png)

**Comment by GregVido** [comment]
I didn't find a solution, I think it's a problem with your Windows 11, I'm limited with Windows 11 API, sorry.
