### ISSUE TITLE
Stated as compatible with Win10 but runtime error saying otherwise

### ISSUE THREAD

**Issue by NicolasConstant** [GregVido/mica-electron#14]
Hi! 

I'm trying to make MicaElectron work on Win10 (build and run), I managed to install the various dependencies (c++ deps etc) but now I have this error on runtime: 

![image](https://user-images.githubusercontent.com/5437247/221756152-df78adb0-978b-449a-9677-e44482b54f49.png)

Electron: 23.1.0
Node: 18.10.0

**Comment by GregVido** [comment]
Hello Im not at Home, I fix it in 2 days sorry, I send message when it will be fix

**Comment by GregVido** [comment]
Hello, I updated it, it's fixed !
