### ISSUE TITLE
If set frame: false, the window is black

### ISSUE THREAD

**Issue by Nevodev** [GregVido/mica-electron#2]
const win = new MicaBrowserWindow({
        width: 800,
        height: 600,
        effect: EFFECT.BACKGROUND.MICA,
        theme: PARAMS.THEME.AUTO,
        autoHideMenuBar: true,
        show: false,
    });

If you add a line "frame: false", the windows is black

**Comment by GregVido** [comment]
It's a problem of Windows 11, the API no work when window didn't have frame

**Comment by GregVido** [comment]
I will find a solution but I'm not sure I'll succeed, I'll let you know

**Comment by Nevodev** [comment]
> I will find a solution but I'm not sure I'll succeed, I'll let you know

Thanks very much!

**Comment by GregVido** [comment]
> > I will find a solution but I'm not sure I'll succeed, I'll let you know
> 
> Thanks very much!

I think it's impossible because when I remove frame with C++, electron crash, sorry ...

**Comment by GregVido** [comment]
> > I will find a solution but I'm not sure I'll succeed, I'll let you know
> 
> Thanks very much!

Hello, I have update the Github, it's now possible !

**Comment by Nevodev** [comment]
> > > I will find a solution but I'm not sure I'll succeed, I'll let you know
> > 
> > 
> > Thanks very much!
> 
> Hello, I have update the Github, it's now possible !

Okay!
