### ISSUE TITLE
Can't run in windows 10

### ISSUE THREAD

**Issue by tonylu110** [GregVido/mica-electron#20]
I set using `setAcrylic` in except Windows 11, but it's can't run
```javascript
if (IS_WINDOWS_11)
  mainWindow.setMicaAcrylicEffect()
else
  mainWindow.setAcrylic()
```

![_7C969813-0A2F-2C84-D50C-F37969BC757E_.png](https://s2.loli.net/2023/07/12/pWO78U1i92EfNAc.png)

**Comment by GregVido** [comment]
Hi, normally it's fixed!

**Comment by tonylu110** [comment]
> Hi, normally it's fixed!

Thinks
