### ISSUE TITLE
Mica-Acrylic doesn't work after upgrading the version to electron-v27.0.0.beta.8 

### ISSUE THREAD

**Issue by JellyBrick** [GregVido/mica-electron#27]
Possibly related issue: https://github.com/electron/electron/pull/39895

**Comment by GregVido** [comment]
Hi ! Thanks for the info, I started to repair it, unfortunately the maximize doesn't work yet, I don't have much time at the moment to repair that, I'll keep you informed!

**Comment by JellyBrick** [comment]
Could that issue be related to the issue https://github.com/electron/electron/pull/39708, and https://github.com/electron/electron/issues/40039?

**Comment by GregVido** [comment]
I think the problem is due to this: https://github.com/electron/electron/pull/40003

**Comment by GregVido** [comment]
sorry, I think you're right actually

**Comment by JellyBrick** [comment]
It seems fixed at mica-electron v1.5.1! Thanks!
