### ISSUE TITLE
version 1.0.9 is built using an old node.js version

### ISSUE THREAD

**Issue by yazninja** [GregVido/mica-electron#3]
![image](https://user-images.githubusercontent.com/71800112/194802272-c5ad6c1c-1b7a-42c0-8c01-2ff8ba4369df.png)

Please recompile with a newer NODE_MODULE_VERSION to support latest nodejs

**Comment by GregVido** [comment]
> ![image](https://user-images.githubusercontent.com/71800112/194802272-c5ad6c1c-1b7a-42c0-8c01-2ff8ba4369df.png)
> 
> Please recompile with a newer NODE_MODULE_VERSION to support latest nodejs

Ok, I will fix it in the weekend

**Comment by GregVido** [comment]
> ![image](https://user-images.githubusercontent.com/71800112/194802272-c5ad6c1c-1b7a-42c0-8c01-2ff8ba4369df.png)
> 
> Please recompile with a newer NODE_MODULE_VERSION to support latest nodejs

Normally it is fixed, I added FAQ in README to help you.

**Comment by Soahr** [comment]
Hi !
The fix didn't worked for me sadly ...

**Comment by GregVido** [comment]
> Hi ! The fix didn't worked for me sadly ...

Are you try to rebuild the projet ?

**Comment by Soahr** [comment]
I have this error with electron-rebuild :

```
An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\[ ... ]\node_modules\mica-electron'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" failed with exit code: 1"
```

Do you have an idea ?

**Comment by GregVido** [comment]
No idea but if you run the comand with --debug argument, what it say ?

**Comment by Soahr** [comment]
Nothing more :s
What is the node version you used to compile the package ?

**Comment by GregVido** [comment]
I use v18.10.0

**Comment by Nevodev** [comment]
> > Hi ! The fix didn't worked for me sadly ...
> 
> Are you try to rebuild the projet ?

I tried to rebuild the project, and it said Rebuild Complete, but when I try to run, it still have this error
<img width="341" alt="image" src="https://user-images.githubusercontent.com/51047891/196015976-6e1393c8-67be-454b-b4f4-316085b61af8.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/51047891/196015985-84f91600-280e-4450-ace9-0e27c2eeecad.png">

**Comment by GregVido** [comment]
> > > Hi ! The fix didn't worked for me sadly ...
> > 
> > 
> > Are you try to rebuild the projet ?
> 
> I tried to rebuild the project, and it said Rebuild Complete, but when I try to run, it still have this error <img alt="image" width="341" src="https://user-images.githubusercontent.com/51047891/196015976-6e1393c8-67be-454b-b4f4-316085b61af8.png"> <img alt="image" width="419" src="https://user-images.githubusercontent.com/51047891/196015985-84f91600-280e-4450-ace9-0e27c2eeecad.png">

try to do this commands in this order:

npm install mica-electron
cd .\node_modules\mica-electron\
node-gyp rebuild
cd ..\\..\\
npm install electron
npm install electron-rebuild
.\node_modules\.bin\electron-rebuild

**Comment by Nevodev** [comment]
> node-gyp rebuild

I got this error when node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Nevabc\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.25217
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nevabc\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Proj\test-pack\node_modules\mica-electron
gyp ERR! node -v v18.11.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok

**Comment by GregVido** [comment]
You don't have more details about the error ?

**Comment by Nevodev** [comment]
> You don't have more details about the error ?

This is all

gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@18.11.0 | win32 | x64
gyp info find Python using Python version 3.10.8 found at "C:\Python310\python.exe"
gyp info find VS using VS2019 (16.11.32901.82) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Nevabc\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Proj\\test-pack\\node_modules\\mica-electron\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Nevabc\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Nevabc\\AppData\\Local\\node-gyp\\Cache\\18.11.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Nevabc\\AppData\\Local\\node-gyp\\Cache\\18.11.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Nevabc\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Nevabc\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.11.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Proj\\test-pack\\node_modules\\mica-electron',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Proj\\test-pack\\node_modules\\mica-electron\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Proj\test-pack\node_modules\mica-electron) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Nevabc\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.25217
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nevabc\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Proj\test-pack\node_modules\mica-electron
gyp ERR! node -v v18.11.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok

**Comment by GregVido** [comment]
You don't have binding.gyp in \node_modules\mica-electron ?

**Comment by Nevodev** [comment]
> node-gyp rebuild

Oh sorry, I cloned the project from github. node-gyp works now.

**Comment by Nevodev** [comment]
> > > > Hi ! The fix didn't worked for me sadly ...
> > > 
> > > 
> > > Are you try to rebuild the projet ?
> > 
> > 
> > I tried to rebuild the project, and it said Rebuild Complete, but when I try to run, it still have this error <img alt="image" width="341" src="https://user-images.githubusercontent.com/51047891/196015976-6e1393c8-67be-454b-b4f4-316085b61af8.png"> <img alt="image" width="419" src="https://user-images.githubusercontent.com/51047891/196015985-84f91600-280e-4450-ace9-0e27c2eeecad.png">
> 
> try to do this commands in this order:
> 
> npm install mica-electron cd .\node_modules\mica-electron node-gyp rebuild cd ..\..\ npm install electron npm install electron-rebuild .\node_modules.bin\electron-rebuild

I didn't use npm, I just cloned it from github, and it works now. Thank you very much.
