### ISSUE TITLE
[Suggestion] Hope the next version some new adaptive functions can be added.

### ISSUE THREAD

**Issue by few-anlong** [GregVido/mica-electron#30]
I added mica and set auto mode to main.js, and when I tested it in Windows 10, it indicated that Mica did not support Windows 10, so I hope to add the effect of automatically switching to acrylic in Windows10, as well as the dark mode and Auto mode of Windows 10 in the next version.
🙏Thanks.

**Comment by GregVido** [comment]
Hello, normally it is repaired
