### ISSUE TITLE
[BUG] Acrylic not supported on Windows10 using the latest version

### ISSUE THREAD

**Issue by JimHans** [GregVido/mica-electron#31]
Sorry to bother, but after I upgrated mica to the latest version 1.5.3, I found it can't work on Windows10 even using win.setAcrylic(), which will encounter an error saying mica only support Windows11. When using the older version of mica (1.5.0 for example), it works.
Hoping to fix this problem, thanks.

**Comment by GregVido** [comment]
Hi, normally it's repaired 👍

**Comment by JimHans** [comment]
It works. Thanks!
