### ISSUE TITLE
Can't run in windows 10

### ISSUE THREAD

**Issue by FlexWasTaken** [GregVido/mica-electron#34]
`
    const win = new MicaBrowserWindow({width: 800,height: 600,autoHideMenuBar: true,show: false,});

    win.setAcrylic();

    win.loadFile(path.join(__dirname, 'index.html'));

    win.webContents.once('dom-ready', () => {
        win.show();
    });}`
![image](https://github.com/GregVido/mica-electron/assets/111044252/dd7584e4-05ce-46f0-b54a-89b3a30cf088)

**Comment by GregVido** [comment]
Hello, normally it is repaired
