### ISSUE TITLE
weird title bar style when maximize window

### ISSUE THREAD

**Issue by Caffeine19** [GregVido/mica-electron#35]
repo to test:
https://github.com/Caffeine19/mica-electron-maximize-error

![image](https://github.com/GregVido/mica-electron/assets/108726581/8239c393-a05a-4396-b1ac-0e6668b11a8c)
![image](https://github.com/GregVido/mica-electron/assets/108726581/f34ec7bb-f711-47c2-9ff1-acb4a7eb2b3f)

**Comment by tiagorangel2011** [comment]
Using titleBarStyle: 'hidden' works but it also weirdly disables maximize/minimize/etc animations

**Comment by Caffeine19** [comment]
> Using titleBarStyle: 'hidden' works but it also weirdly disables maximize/minimize/etc animations

yep,and when I use hidden,transition in windows resizing disappeared in windows11.

**Comment by GregVido** [comment]
Hello, normally it is repaired
