### ISSUE TITLE
No Animation Effects on Maximize/Minimize

### ISSUE THREAD

**Issue by heyadeivan** [GregVido/mica-electron#7]
hello i used this code
```
frame:false,
titlebarStyle: 'hidden'
```

The Mica was successfully applied, but I made the maximize and minimize buttons myself but there is no minimize or maximize animation effect, can you fix this?

animation only works in state `frame:true`

#bug

**Comment by GregVido** [comment]
> hello i used this code
> 
> ```
> frame:false,
> titlebarStyle: 'hidden'
> ```
> 
> The Mica was successfully applied, but I made the maximize and minimize buttons myself but there is no minimize or maximize animation effect, can you fix this?
> 
> animation only works in state `frame:true`
> 
> #bug

Hello thank you for reporting this bug, I made an update to fix it, you can have the animations now :)
