### ISSUE TITLE
bug: When I try to build, the following problem occurs

### ISSUE THREAD

**Issue by iosyyy** [GregVido/mica-electron#8]
```
was compiled against a different Node.js version using
  NODE_MODULE_VERSION 83. This version of Node.js requires
  NODE_MODULE_VERSION 109. Please try re-compiling or re-installing
```
If you need more detailed information, please reply me, THKS

**Comment by GregVido** [comment]
Hello, are you try to execute this commands:

npm install electron
npm install electron-rebuild
.\node_modules\\.bin\electron-rebuild

And if it doesn' t work, what is your node version ? (node --version)

**Comment by iosyyy** [comment]
I have tried it but the error is the same
and my environment
![image](https://user-images.githubusercontent.com/55818117/208063990-7f8ec39d-ef28-46f9-9c28-bfccca6e72de.png)

```
        "electron": "21.3.3",
        "electron-builder": "^23.6.0",
        "electron-packager": "^17.1.1",
        "mica-electron": "^1.1.7",
        "electron-rebuild": "^3.2.9",
        "node-loader": "^0.6.0",
        "nodejs-base64": "^2.0.0",
```

**Comment by GregVido** [comment]
How your run your project ?

If you write 'electron .' in your terminal, try to write electron --version to see if is the same version as your environment

**Comment by NicolasConstant** [comment]
I'm running into the same issue: I'm using nvm to manage my nodes versions and with node v18.14.2 I can't get through (tried various rebuilds (`npm rebuild`, `.\node_modules\.bin\electron-rebuild`) none did work. 

What version of node are you using on your side?

**Comment by iosyyy** [comment]
The same 19.3.0 as the one I mentioned above

**Comment by NicolasConstant** [comment]
Strange, with `19.3.0` I also have this error: 

![image](https://user-images.githubusercontent.com/5437247/222607054-35ba3408-2f6f-494e-8877-5e341de41f0b.png)

Tried to rebuild (also with node-gyp) but no luck so far: having this error every-time.

**Comment by GregVido** [comment]
Try running with this command:
`npx electron .`

**Comment by iosyyy** [comment]
> Try running with this command: `npx electron .`

I'm not working on this project anymore, but I seem to have tried this method and it didn't work

**Comment by NicolasConstant** [comment]
No luck: 

![image](https://user-images.githubusercontent.com/5437247/222862296-9e02c343-fda8-415e-9db2-30ec30a8615c.png)

@GregVido what is your node version?

**Comment by GregVido** [comment]
I use v18.10.0, but the problem with version is about electron, your electron version isn't the same with the module build.

**Comment by GregVido** [comment]
Hello normally it's fixed!
