### ISSUE TITLE
Can't install mica-electron

### ISSUE THREAD

**Issue by zyrotec** [GregVido/mica-electron#9]
When I try installing the package with "npm i mica-electron" I get a list of errors.
It says The Windows SDK version 10.0.19041.0 was not found but I have it installed.
![Screenshot_20221228_030356](https://user-images.githubusercontent.com/13785776/209741911-6de5dba8-c501-49d9-8449-51461468dc75.png)
![Screenshot_20221228_030420](https://user-images.githubusercontent.com/13785776/209741967-9f5f846b-3730-4086-bb0a-4945d31d41a9.png)

**Comment by GregVido** [comment]
Hello, did you try to do this ?
https://stackoverflow.com/questions/57879150/how-can-i-solve-error-gypgyp-errerr-find-vsfind-vs-msvs-version-not-set-from-c

**Comment by zyrotec** [comment]
I just needed to update my Visual Studio. Installation worked.
